# Site settings
title: The Reading Line
email: thereadingline@gmail.com
description: "The Reading Line is an amazing organization that hosts book rides annually."
url: http://thereadingline.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/thereadingline
  - title: facebook
    url: https://www.facebook.com/thereadingline
  - title: instagram
    url: https://www.instagram.com/thereadingline/
  - title: envelope-o
    url: mailto:jjwilson@penguinrandomhouse.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

include: [_pages]
